apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qoss
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qoss
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qoss
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qoss
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qoss
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xsdh-tenant/rhtap-demo-app/hacbs-test-project-qoss@sha256:58f1d17017fe1954c294fa3e998534f6fe6540561a30e34612b6a9b5ade37307
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
